name: phonopy test using conda-forge environment with openmp

on:
  push:
    branches-ignore:
    - publish-gh-pages
    - develop
    - master
    - rc
  pull_request:
    branches: [ develop ]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11"]

    steps:
    - uses: actions/checkout@v3
    - uses: conda-incubator/setup-miniconda@v2
      with:
        miniforge-version: latest
    - name: Install dependencies
      run: |
        conda activate test
        conda install --yes -c conda-forge python=${{ matrix.python-version }}
        conda install --yes -c conda-forge matplotlib-base pyyaml scipy numpy spglib h5py pip pytest codecov pytest-cov pytest cmake c-compiler
    - name: Install cp2k-input-tools
      run: |
        conda activate test
        pip install cp2k-input-tools
    - name: Setup phonopy
      run: |
        conda activate test
        export PHONOPY_USE_OPENMP=true
        pip install -e . -vvv
    - name: Test with pytest
      run: |
        conda activate test
        pytest --cov=./ --cov-report=xml
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        verbose: true
